create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying null default '30'::character varying,
  email character varying not null default '50'::character varying,
  is_expert boolean not null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email)
) TABLESPACE pg_default;

create table public.symptoms (
  id bigint generated by default as identity not null,
  name text not null,
  description text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  code character varying(10) not null,
  image text null,
  constraint symptoms_pkey primary key (id),
  constraint symptoms_code_unique unique (code)
) TABLESPACE pg_default;

create table public.diseases (
  id bigint generated by default as identity not null,
  name text not null,
  symptoms integer[] not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  code character varying(10) not null,
  solution jsonb not null default '{"desc": "", "link": null, "list": null, "image": null}'::jsonb,
  about text not null default ''::text,
  constraint diseases_pkey primary key (id),
  constraint diseases_code_unique unique (code),
  constraint solution_json_structure check (
    (
      (jsonb_typeof(solution) = 'object'::text)
      and (solution ? 'desc'::text)
      and (solution ? 'image'::text)
      and (solution ? 'list'::text)
      and (solution ? 'link'::text)
      and ((solution ->> 'desc'::text) is not null)
      and (
        ((solution ->> 'image'::text) is null)
        or (
          jsonb_typeof((solution -> 'image'::text)) = 'string'::text
        )
      )
      and (
        ((solution ->> 'list'::text) is null)
        or (
          jsonb_typeof((solution -> 'list'::text)) = 'string'::text
        )
      )
      and (
        ((solution ->> 'link'::text) is null)
        or (
          jsonb_typeof((solution -> 'link'::text)) = 'string'::text
        )
      )
    )
  )
) TABLESPACE pg_default;